[package]
name = "duklang"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
logos = "0.15.0"
logos-iter = "0.1.3"
owo-colors = "4.2.1"
rustyline = "16.0.0"
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.12"
